### ISSUE TITLE
feat: View all todo lists

### ISSUE THREAD

**Issue by dalyIsaac** [dalyIsaac/mstodo#1]
- [x] View lists 96df5de8a0e2bee0f7b7f0a27a670ae4cc77ebfc
- [x] Filter by name 6d5eeb32c2cbd91474db3e1de91f5a8765c2d82e
- [x] Sort baccfbb590546c2aea4553c6878c1d0989508324
- [x] Show id 4d6201345de4e1a68d802cf18c5bc1ae6ae0dd09
- [x] Exclude columns c074b474f02d43b289939d834077167120d154ca
